### ISSUE TITLE
Define bundler tool

### ISSUE THREAD

**Issue by thiagomini** [TrilonIO/eslint-plugin#5]
# Description

We should define which bundler tool we want to use to publish this package. A few things to take into consideration:

* How do we configure that bundler to map the `tsconfig.paths` so we can use path aliases?
* Is it possible to bundle/compile our code for both CJS and ESM? (Example: [pkgroll](https://github.com/privatenumber/pkgroll))

## Acceptance Criteria
A bundler and its configuration are created so that the requirements above are answered/met.

**Comment by tuxmachine** [comment]
[CJS](https://github.com/eslint/eslint/issues/15453#issuecomment-1001200953) is still the default. ESM is supported, but the syntax is a awkward IMHO.

Also, I think [TSC](https://www.typescriptlang.org/tsconfig#module) should do fine and is by far the simplest 😄 since it's a devtool, I don't think we need a bundler right?

**Comment by thiagomini** [comment]
Hey Rick, thanks for the feedback! But I meant to use something that transforms custom paths defined in the tsconfig file like `@src/...` to their actual counterpart. Does TSC transform those paths? I believe we need additional tools to accomplish this

**Comment by tuxmachine** [comment]
Ah you're right, I always forget that one when setting up new projects.

In that case we could use a bundler, or something like https://www.npmjs.com/package/tsc-alias

Any preferences?
